apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: {{ .Values.letsencryptIssuerRef }}
spec:
  selfSigned: {}
  # acme:
  #   server: {{ .Values.letsencrpytAcmeServer }}
  #   email: {{ .Values.email }}
  #   privateKeySecretRef:
  #     name: {{ .Values.letsencryptIssuerRef }}
  #   solvers:
  #   - dns01:
  #       cloudDNS:
  #         project: {{ .Values.dnsProject }}
  #         serviceAccountSecretRef:
  #           name: clouddns-service-account
  #           key: key.json
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: "{{ .Values.nameSpace }}-cert"
  namespace: {{ .Values.nameSpace }}
spec:
  secretName: "{{ .Values.nameSpace }}-tls"
  duration: 2160h
  renewBefore: 720h
  issuerRef:
    name: {{ .Values.letsencryptIssuerRef }}
    kind: ClusterIssuer
  commonName: {{ .Values.defaultHost }}
  dnsNames:
    - {{ .Values.defaultHost }}
    {{- range .Values.users }}
    - {{ .host }}
    {{- end }}
  privateKey:
    rotationPolicy: Always
    algorithm: RSA
    encoding: PKCS8
    size: 2048
  additionalOutputFormats:
    - type: CombinedPEM
  usages:
    - digital signature
    - key encipherment
    - server auth
