# CRD Definition
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: pingresources.example.com
spec:
  group: example.com
  names:
    plural: pingresources
    singular: pingresource
    kind: PingResource
  scope: Namespaced
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                message:
                  type: string
            status:
              type: object
              properties:
                response:
                  type: string

---

# Role Definition for Updating Status
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: ping-operator-role
  namespace: default
rules:
  - apiGroups: ["example.com"]
    resources: ["pingresources"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["example.com"]
    resources: ["pingresources/status"]
    verbs: ["get", "update", "patch"]

---

# RoleBinding to Attach Role to the Default ServiceAccount
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: ping-operator-rolebinding
  namespace: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: ping-operator-role
subjects:
  - kind: ServiceAccount
    name: default
    namespace: default
