# ServiceAccount for the Operator
apiVersion: v1
kind: ServiceAccount
metadata:
  name: ping-operator-sa
  namespace: default

---

# Role for the Operator to access PingResource resources and their status fields
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: ping-operator-role
  namespace: default
rules:
  - apiGroups: ["example.com"]
    resources: ["pingresources"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["example.com"]
    resources: ["pingresources/status"]
    verbs: ["get", "update", "patch"]

---

# RoleBinding to attach the Role to the ServiceAccount
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: ping-operator-rolebinding
  namespace: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: ping-operator-role
subjects:
  - kind: ServiceAccount
    name: ping-operator-sa
    namespace: default

---

# Deployment for the Operator
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ping-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ping-operator
  template:
    metadata:
      labels:
        app: ping-operator
    spec:
      serviceAccountName: ping-operator-sa
      containers:
        - name: ping-operator
          image: europe-west2-docker.pkg.dev/team-aura-networking/ping-operator-repo/ping-operator:latest
          imagePullPolicy: Always
