---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: endpoints
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: endpoints
  template:
    metadata:
      labels:
        app: endpoints
    spec:
      serviceAccountName: cluster-ksa
      containers:
        - name: endpoints
          image: europe-west2-docker.pkg.dev/prj-hub-lab/g5-hub-eu-repo/endpoints:latest
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: endpoints
  namespace: default
spec:
  type: ClusterIP
  selector:
    app: endpoints
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
