apiVersion: skaffold/v2beta8
kind: Config
build:
  tagPolicy:
    envTemplate:
      template: "{{.VERSION}}"
  artifacts:
    - image: europe-west2-docker.pkg.dev/YOUR_PROJECT_ID/g1-hub-eu-repo/ping-operator
      context: ping/app/operator
    - image: europe-west2-docker.pkg.dev/YOUR_PROJECT_ID/g1-hub-eu-repo/control-plane
      context: ping/app/control-plane
    - image: europe-west2-docker.pkg.dev/YOUR_PROJECT_ID/g1-hub-eu-repo/api-server
      context: ping/app/api-server
deploy:
  kustomize:
    paths:
      - ping/manifests/kustomize/base
      - ping/manifests/kustomize/overlays/load-balancers
