# artifacts/ping/manifests/kustomize/overlays/load-balancers/control-plane.yaml
apiVersion: v1
kind: Service
metadata:
  name: control-plane-elb
  namespace: default
spec:
  type: LoadBalancer
  selector:
    app: control-plane
  ports:
    - protocol: TCP
      port: 80
      targetPort: 9000
