apiVersion: apps/v1
kind: Deployment
metadata:
  name: control-plane
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: control-plane
  template:
    metadata:
      labels:
        app: control-plane
    spec:
      serviceAccountName: default
      containers:
        - name: control-plane
          image: europe-west2-docker.pkg.dev/prj-hub-lab/g5-hub-eu-repo/control-plane
          ports:
            - containerPort: 9000
---
apiVersion: v1
kind: Service
metadata:
  name: control-plane
  namespace: default
spec:
  type: ClusterIP
  selector:
    app: control-plane
  ports:
    - protocol: TCP
      port: 9000
      targetPort: 9000
