# ServiceAccount for the Operator
apiVersion: v1
kind: ServiceAccount
metadata:
  name: ping-operator-sa
  namespace: default

---
# ClusterRole for Cluster-level Access
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: ping-operator-cluster-role
rules:
  - apiGroups: ["example.com"]
    resources: ["pingresources"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["apiextensions.k8s.io"]
    resources: ["customresourcedefinitions"]
    verbs: ["get", "list", "watch"]

---
# ClusterRoleBinding for Cluster Access
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: ping-operator-cluster-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: ping-operator-cluster-role
subjects:
  - kind: ServiceAccount
    name: ping-operator-sa
    namespace: default

---
# Role for Namespace-level Access
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: ping-operator-namespace-role
  namespace: default
rules:
  - apiGroups: ["example.com"]
    resources: ["pingresources"]
    verbs: ["get", "list", "watch", "create", "delete", "update", "patch"]
  - apiGroups: ["example.com"]
    resources: ["pingresources/status"]
    verbs: ["get", "update", "patch"]

---
# RoleBinding for Namespace Access
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: ping-operator-namespace-rolebinding
  namespace: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: ping-operator-namespace-role
subjects:
  - kind: ServiceAccount
    name: ping-operator-sa
    namespace: default

---
# Role for Control Plane
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: control-plane-role
  namespace: default
rules:
  - apiGroups: ["example.com"]
    resources: ["pingresources"]
    verbs: ["get", "list", "watch", "create", "delete", "update", "patch"]
  - apiGroups: ["example.com"]
    resources: ["pingresources/status"]
    verbs: ["get", "update", "patch"]

---
# RoleBinding for Control Plane
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: control-plane-rolebinding
  namespace: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: control-plane-role
subjects:
  - kind: ServiceAccount
    name: default
    namespace: default

---
# Deployment for the Operator
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ping-operator
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ping-operator
  template:
    metadata:
      labels:
        app: ping-operator
    spec:
      serviceAccountName: ping-operator-sa
      containers:
        - name: ping-operator
          image: europe-west2-docker.pkg.dev/prj-hub-lab/g5-hub-eu-repo/ping-operator:latest
          imagePullPolicy: Always
