apiVersion: v1
kind: Service
metadata:
  name: api-server-elb
  namespace: default
spec:
  type: LoadBalancer
  selector:
    app: api-server
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
