---
apiVersion: v1
kind: Service
metadata:
  name: endpoints-lb
  namespace: default
spec:
  type: LoadBalancer
  selector:
    app: endpoints
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
