services:
  http-80:
    container_name: http-80
    hostname: -DCK-http-80
    build:
      context: ./app/app
      dockerfile: Dockerfile
    environment:
      HOST_HOSTNAME: $${HOSTNAME}
    network_mode: host
    command: uvicorn main:app --host '0.0.0.0' --port 80
    restart: always
  http-ipv6-80:
    container_name: http-ipv6-80
    hostname: -DCK-http-ipv6-80
    build:
      context: ./app/app
      dockerfile: Dockerfile
    environment:
      HOST_HOSTNAME: $${HOSTNAME}
    network_mode: host
    command: uvicorn main:app --host '::' --port 80
    restart: always
