# CRD Definition for Orchestra Custom Resource
# Defines the `orchestra` Custom Resource, which allows users to
# specify Kubernetes clusters (orchestras) with their respective attributes.
# This will be used by the cluster-operator for service discovery (cluster pods).
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: orchestras.example.com
spec:
  group: example.com
  names:
    plural: orchestras
    singular: orchestra
    kind: Orchestra
  scope: Namespaced
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                orchestraName:
                  type: string
                region:
                  type: string
                  nullable: true
                zone:
                  type: string
                  nullable: true
                project:
                  type: string
              oneOf:
                - required: ["region"]
                - required: ["zone"]
            status:
              type: object
              properties:
                state:
                  type: string

---

# Role Definition for Updating Status
# Grants permissions to the Orchestra Operator to manage and update
# the status of Orchestra custom resources within the namespace.
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: orchestra-operator-role
  namespace: default
rules:
  - apiGroups: ["example.com"]
    resources: ["orchestras"]
    verbs: ["get", "list", "watch", "update", "patch"]
  - apiGroups: ["example.com"]
    resources: ["orchestras/status"]
    verbs: ["get", "update", "patch"]

---

# RoleBinding to Attach Role to the Default ServiceAccount
# Binds the `orchestra-operator-role` to the default ServiceAccount,
# allowing it to access Orchestra resources in the default namespace.
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: orchestra-operator-rolebinding
  namespace: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: orchestra-operator-role
subjects:
  - kind: ServiceAccount
    name: default
    namespace: default
