# CRD Definition for Orchestra Custom Resource
# Defines the `orchestra` Custom Resource, which allows users to
# specify Kubernetes clusters (orchestras) with their respective attributes.
# This will be used by the cluster-operator for service discovery (cluster pods).
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: orchestras.example.com
spec:
  group: example.com
  names:
    plural: orchestras
    singular: orchestra
    kind: Orchestra
  scope: Namespaced
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                name:
                  type: string
                region:
                  type: string
                  nullable: true
                zone:
                  type: string
                  nullable: true
                project:
                  type: string
                ingress:
                  type: string
              oneOf:
                - required: ["region"]
                - required: ["zone"]
            status:
              type: object
              properties:
                state:
                  type: string
